let CSK = [
    {
        playerID : 1,
        playerName : "MS. Dhoni",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/57.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Ruturaj Gaikwad",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/102.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Devon Conway",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2023/601.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Ajinkya Rahane",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/44.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Sameer Rizvi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1229.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Ravindra Jadeja",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/46.png",
        pplayerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Shivam Dube",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/211.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Mitchell Santner",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/75.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Moeen Ali",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/206.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Rachin Ravindra",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/724.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Daryl Mitchell",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/83.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Shardul Thakur",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/105.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Ajay Mandal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1931.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Nishant Sindhu",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/791.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Deepak Chahar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/91.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Mukesh Choudhary",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/970.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Mustfizur Rahman",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/258.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Tushar Deshpande",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/539.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Matheesha Pathirana",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1014.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Maheesh Theekshana",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/629.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default CSK;