let GT = [
    {
        playerID : 1,
        playerName : "Shubhman Gill",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/62.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Kane Williamson",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/65.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "David Miller",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/128.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Sai Sudharshan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/976.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "BR Sharath",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3117.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Wriddhiman Saha",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/225.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Abhinav Manohar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/974.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Matthwe Wade",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/549.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Vijay Shankar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/61.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Shahrukh Khan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/590.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Azmattullah Omarzai",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1354.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Rahul Tewatia",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/120.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Darshan Nalkande",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/127.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Rashid Khan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/218.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Mohammad Shami",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2023/47.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Umesh Yadav",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/21.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Spencer Johnson",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2518.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Mohit Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/100.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Noor Ahmad",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/975.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Joshua Little",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/678.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default GT;