let KKR = [
    {
        playerID : 1,
        playerName : "Shreyas Iyer",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/12.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Rahmanullah Gurbaz",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/641.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Nitish Rana",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/148.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Manish Pandey",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/16.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Rinku Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/152.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Phil Salt",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1220.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Angkrish Raghuvanshi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/787.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 8,
        playerName : "K.S. Bharat",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/365.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Sunil Narine",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/156.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Andre Russel",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/141.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Venktesh Iyer",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/584.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Ramandeep Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/991.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Anukul Roy",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/160.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Harshit Rana",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1013.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Suyash Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1932.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Mitchell Starc",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/31.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Varun Chakravarthy",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/140.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Vaibhav Arora",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/583.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Dushmanta Chameera",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/608.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Chetan Sakariya",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/592.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default KKR;