let LSG = [
    {
        playerID : 1,
        playerName : "KL Rahul",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/19.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Devdutt Padikkal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/200.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Quinton De Kock",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/170.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Nicholas Puran",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/136.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Ashton Turner",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/86.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Deepak Hooda",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/215.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Krunal Pandya",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/17.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Marcus Stoinis",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/23.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Ayush Badoni",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/985.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Arshad Khan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/988.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "K. Gowtham",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/179.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Shivam Mavi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/154.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Ravi Bishnoi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/520.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Yash Thakur",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1550.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Naveen Ul Haq",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/639.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Matt Henry",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/71.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Shamar Joseph",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3105.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Mohsin Khan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/541.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Amit Mishra",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/107.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Mayank Yadav",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/987.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default LSG;