let MI = [
    {
        playerID : 1,
        playerName : "Rohit Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/6.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Ishan Kishan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/164.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Suryakumar Yadav",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/174.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "N. Tilak Kumar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/993.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Hardik Pandya",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/54.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Nehal Wadhera",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1541.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Romario Shepherd",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/371.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Jasprit Bumrah",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/9.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Akash Madhwal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1045.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Piyush Chawla",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/149.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Gerlad Coetzee",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2535.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Dewald Bravis",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/797.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Harvik Desai",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3154.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Tim David",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/636.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Vishnu Vinod",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/581.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Mohammad Nabi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/217.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Kartikeya Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1015.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Shams Mulani",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/600.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Shreyas Gopal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/192.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Arjun Tendulkar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/585.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
]

export default MI;