let PK = [
    {
        playerID : 1,
        playerName : "Shikhar Dhawan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/11.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Jonny Bairstow",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/216.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "P Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/137.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Shashank Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/191.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Ashutosh Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3109.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Jitesh Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1000.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Rilee Rossouw",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1426.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Harpreet Bhatia",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1934.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Liam Livingstone",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/183.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Sam Curren",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/138.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Sikandar Raza",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/820.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Rishi Dhawan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/996.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Chris Woakes",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/314.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Atharva Taide",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1001.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Arshdeep Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/125.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Kagiso Rabada",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/116.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Rahul Chahar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/171.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Harshal Patel",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/114.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Harpreet Brar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/130.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Nathan Ellis",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/633.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default PK;