let RCB = [
    {
        playerID : 1,
        playerName : "Virat Kohli",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Faf-Du-Plessis",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/94.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Rajat Patidar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/597.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Anuj Rawat",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/534.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Will Jacks",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1941.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Dinesh Karthik",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/13.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Suyash Parabhudessai",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/598.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Saurav Chavan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3114.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Mayank Dagar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1547.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Glenn Maxwell",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/28.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Mahipal Lomror",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/184.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Cameron Green",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/550.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Swapnil Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1483.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Karn Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/98.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Mohammed Siraj",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/63.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Lokie Ferguson",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/69.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Yash Dayal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/978.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Akash Deep",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1007.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Reece Topley",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/574.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Vyshak Vijay Kumar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2034.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default RCB;