let RR = [
    {
        playerID : 1,
        playerName : "Sanju Samson",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/190.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Jos Buttler",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/182.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Yashasvi Jaiswal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/533.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Riyan Parag",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/189.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Shimron Hetmyer",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/210.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Dhruv Jurel",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1004.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Rovman Powell",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/329.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Shubham Dubey",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3112.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 9,
        playerName : "R. Ashwin",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/45.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Tanush Kotian",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/3118.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Abid Mushtaq",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1591.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Avesh Khan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/109.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Kuldeep Sen",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1005.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Keshav Maharaj",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/347.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 15,
        playerName : "Yuzvendra Chahal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/10.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Trent Boult",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/66.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Sandeep Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/220.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Nandre Burger",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2806.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Kunal Rathore",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1540.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Donovan Ferreira",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/2033.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default RR;