let SRH = [
    {
        playerID : 1,
        playerName : "Mayank Agarwal",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/55.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 2,
        playerName : "Travis Head",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/37.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 3,
        playerName : "Aiden Markram",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/287.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 4,
        playerName : "Rahul Tripathi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/188.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 5,
        playerName : "Glenn Phillips",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/635.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 6,
        playerName : "Heinrich Klassen",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/202.png",
        playerRole : "Batter-WK",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-wicket-keeper-icon.svg",
    },
    {
        playerID : 7,
        playerName : "Abhishek Sharma",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/212.png",
        playerRole : "Batter",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-batsman-icon.svg",
    },
    {
        playerID : 8,
        playerName : "Marco Jansen",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/586.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 9,
        playerName : "Washington Sundar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/20.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 10,
        playerName : "Sanvir Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1943.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 11,
        playerName : "Nitish Kumar Reddy",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/1944.png",
        playerRole : "All Rounder",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-all-rounder-icon.svg",
    },
    {
        playerID : 12,
        playerName : "Akash Singh",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/535.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 13,
        playerName : "Pat Cummins",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/33.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 14,
        playerName : "Bhuvneshwar Kumar",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/15.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 15,
        playerName : "T Natrajan",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/224.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 16,
        playerName : "Umran Malik",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/637.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 17,
        playerName : "Mayank Markande",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/87.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 18,
        playerName : "Jaydev Unadkat",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/180.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 19,
        playerName : "Shahbaz Ahamad",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/523.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    {
        playerID : 20,
        playerName : "Fazalhaq Farooqi",
        playerImg : "https://documents.iplt20.com/ipl/IPLHeadshot2024/523.png",
        playerRole : "Bowler",
        playerRoleSVG : "https://www.iplt20.com/assets/images/teams-bowler-icon.svg",
    },
    
]

export default SRH;